### ISSUE TITLE
[FEATURE REQUEST] more user friendly GUI, multi-threading

### ISSUE THREAD

**Issue by caissist** [limosoft-de/raffytimelapse#19]
I remember very well the first time I used Raffy Timelaps: an Import button for the photos - self-explanatory, but then I searched in vain for the settings for the video clip ?! Finally I continued with the "Start" button, and voilá! But this is not a logical way for the user.
My suggestion for 3 buttons as a left side panel, permanently displayed:
1. "Import photos"
2. "Settings for the video clip"
3. "Start" for the creation of the video clip

This takes the user by the hand, no more mistakes.

In March I tried a higher resolution than just "Full HD" for about 360 photos. But after 7 days and nights non-stop still no result ?! PC used: Intel Core2 quad under Win7 Prof 64-bit.
I think that multi-threading would be indispensable for such computing-intensive software.

Thank you.

**Comment by limosoft-de** [comment]
**GUI**
Thank you for your insights and proposals on this! I will definitly keep the GUI aspect in mind, however, until now I had very positive feedback on the GUI by many people so I will be careful with making any adjustments.

However, I agree that the button titled "Start" might not be fitting and self-explanatory. Having the button titled "Export"/"Exportieren" might be more useful. I will consider this for the next release.

**Multi-threading**
As Raffy Timelapse is using the popular ffmpeg library, this is slightly "out of my control". There is a `threads` parameter, to determine the amount of threads to use. This setting is set on auto by default (see [ffmpeg documentation](http://ffmpeg.org/ffmpeg-all.html)). As I am not explicitly passing this parameter, this should result in using multi-threading by default.

I will check that this behavior is indeed functioning properly and report back.

**Comment by caissist** [comment]
> **Multi-threading**
> As I am not explicitly passing this parameter, this should result in using multi-threading by default.

Well, I had a look into Windows Task Manager while running Raffy Timelaps and found:
- running just as 32-bit application
- no multi-threading
![Raffy Timelapse - Windows Task Manager - 32-bit + no multithreading](https://user-images.githubusercontent.com/4838604/85919548-5fb68f80-b86c-11ea-9a6b-46b14681efd9.jpg)

**Comment by caissist** [comment]
> **GUI**
> I will definitly keep the GUI aspect in mind, however, until now I had very positive feedback on the GUI by many people so I will 
> be careful with making any adjustments.

It is a very demanding but absolutely necessary thing to create a true user-friendly user interface (GUI). Unfortunately, the general way of thinking about that is not adequately developed.
I have had some experience of helping developing software, and so I know that the user guidance is unfortunately not successful here. In other words: excellent programmed software is difficult to use if it is not easy to use for any user.

**Comment by limosoft-de** [comment]
Hi @caissist ,

**Multithreading**

1. The application showing up as 32-bit in Task Manager is a bit of AnyCPU madness going on, which I already discovered (thanks to your remarks) in #18. This will be fixed in the next release, thanks for pointing that out again though.
2.  Your screenshot does not provide any insights on the usage of multithreading. You will have to look into the Resource Monitor to get more information on that, but you possibly attached this only for the point above anyways, right? Because not only is Raffy Timelapse using multithreading (not sure why you came to the conclusion that it isn't) for processes like Importing images etc, the rendering is done by the ffmpeg library, which runs as a separate process (`ffmpeg.exe`/ `ffmpeg64.exe`). I just checked, and ffmpeg is actually using multithreading and all CPU cores available just as expected. So rest assured, that multithreading is indeed available and being used. Not sure why your mentioned job didn't go through, but I am assuming there was some uncaught error for some reason, which will be hard to analyze without any log files.

![RaffyTimelapse_multithreading](https://user-images.githubusercontent.com/5230690/85948922-e5f9d100-b953-11ea-8741-896272a00b24.jpg)
![RaffyTimelapse_cpuUsage](https://user-images.githubusercontent.com/5230690/85948921-e5613a80-b953-11ea-82db-54eec2b88a8f.jpg)


**GUI**
Again, thank you for your input on that matter. I would just kindly ask you to keep some things in mind:

1. The GUI is designed mainly for users who are either used to video editing software in general or have no experience with software like this at all. The first user group will be used to having the export settings as part of the export routine (Adobe Premiere Pro, Sony Vegas, HitFilm,... come to mind), as these settings might be individual for any export and are not necessarily project based. The second user group will probably not be aware of the many video settings to choose from and therefor probably ignore an additional settings dialogue. This will however most likely lead to unexpected results and frustrated users. That's why I decide to design it that way.
2. So far I've only gotten positive reviews from professional software tester on the GUI, including [here](https://www.softpedia.com/get/Multimedia/Graphic/Graphic-Others/Raffy-Timelapse.shtml) and [here](http://raffy-timelapse.findmysoft.com/). I am not saying that your opinion is therefor wrong, but as you probably know, given your experience, designing a user friendly UI is also a slightly subjective matter at some points. There is never an ultimate solution, you can always just come as close as possible. Therefor, and giving the mainly positive reviews so far, I will rather stick to the current UI than making intense changes until I get more critical feedback on that aspect.
3. Please keep in mind that this started out as a software just for my own. I just published it, as I thought other people might benefit from it. I am not making any money from this project at all and do have a full time job and many other responsibilities to work on in my free time. So I only have limited time and resources to work on Raffy Timelapse, thats why the application will probably never be a perfect application. I am sorry, but that is just what it is.

**Comment by caissist** [comment]
Hello and thanks for your reply.

> **Multithreading**
> 2\. Your screenshot does not provide any insights on the usage of multithreading. You will have to look into the Resource Monitor to get more information on that, but you possibly attached this only for the point above anyways, right? 

Right.

> 2\. [...] Because not only is Raffy Timelapse using multithreading (not sure why you came to the conclusion that it isn't) 

Well, I installed Timelaps on a third comp under Windows 10 Prof 64-bit and observed Windows Task Manager and Windows Ressourcen Manager while running Timelaps (and other software, too), see here:

![Ressourcenmonitor while Timelaps is running - CPUs](https://user-images.githubusercontent.com/4838604/85952496-06cd2100-b96a-11ea-8e5e-336807ffadfa.PNG)

![Windows Taskmanager while Timelaps is running - CPUs](https://user-images.githubusercontent.com/4838604/85952508-151b3d00-b96a-11ea-9da6-215f50f20fdc.PNG)

> 2\. [...] for processes like Importing images etc, the rendering is done by the ffmpeg library, which runs as a separate process (`ffmpeg.exe`/ `ffmpeg64.exe`). 

I do know. But to my surprise I missed ffmpeg library, see here:

![Ressourcenmonitor while Timelaps is running - processes](https://user-images.githubusercontent.com/4838604/85952579-a25e9180-b96a-11ea-8d0b-31e24b9add53.PNG)

> 2\. [...] I just checked, and ffmpeg is actually using multithreading and all CPU cores available just as expected.

Thank you! Yeah, that way it should look but not here?!

> 2\. [...] which will be hard to analyze without any log files

Edit: found and enclosed.
[Raffy Timelapse - log.txt](https://github.com/limosoft-de/raffytimelapse/files/4851096/Raffy.Timelapse.-.log.txt)


> **GUI**
> 3\. I just published it, as I thought other people might benefit from it. I am not making any money from this project at all and do have a full time job and many other responsibilities to work on in my free time. So I only have limited time and resources to work on Raffy Timelapse, thats why the application will probably never be a perfect application. I am sorry, but that is just what it is.

I understand and respect it, of course.
Thank you.

**Comment by limosoft-de** [comment]
Sorry, just realized that you answered again after the Issue was closed already, so a quick statement to your new entries:

1. You probably didn't find ffmpeg, as the process is only started when the Export is running. After the Export is finsihed, the process will be terminated. So you will have to check the Resources Manager/Task Manager during the Export phase. Then you should also be able to confirm the use of multiple cores.
2. According to the attached log, the Export finished after roughly 3 minutes. However, I am guessing this is not the log of the faulty export you mentioned, but from a recent successfull one. Only the latest log is stored, all prior entries will be overridden each time. So if any error like this occurs again, please feel free to post the log right away in a new Ticket/Issue and I will take a look at it!
