### ISSUE TITLE
[QUESTION] Inactive Translation Project?

### ISSUE THREAD

**Issue by caissist** [limosoft-de/raffytimelapse#21]
Using Raffy Timelaps over the time I noticed some weaknesses/mistakes in German translation and tried to pick up your offer for supporting your project but failed?! Screenshot enclosed.
![Raffy Timelaps - Translation menu without workflow](https://user-images.githubusercontent.com/4838604/85230001-86e50b00-b3ed-11ea-8049-29784e6d1304.jpg)

**Comment by limosoft-de** [comment]
Hi @caissist,

the project was automatically archived on June 28th by Poeditor due to an inactivity in the project for 6 month, however I just restored it again.

Please feel free to contribute to any languages you feel confortable with. As for the German translations, I would just kindly ask you to stick with the "Du" form.

Thank you very much for your continued support.
